# fly.toml file generated for corestock on 2022-12-31T09:47:03+08:00

app = "corestock"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  APP_URL = "https://corestock.fly.dev"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "sku-laravel"
  DB_HOST = "ap-southeast.connect.psdb.cloud"
  DB_PASSWORD = "pscale_pw_C1CNrWvCZ034FNehW5Fx0n5uLo3vAOiCW9QJKcNeGkb"
  DB_PORT = "3306"
  DB_USERNAME = "fr89rz5jxjfwztdizlco"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
